version: "3"

networks:
    laravel:
        driver: bridge

services:
    php:
        container_name: php
        build:
            dockerfile: dockerfile
            context: .
        ports:
            - "9000:9000"
        volumes:
            - ./test-laravel:/var/www/app
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        ports:
            - "8001:8001"
        volumes:
            - ./test-laravel:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    
    mysql:
        image:  mysql
        container_name: mysql
        ports:
            -   "3306:3306"
        volumes:
            -   ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel