version: '3'

networks:
  laravel:

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app
    networks:
      - laravel
  
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel